baseurl = "http://springhispano.org"
title = "SpringHispano.org"
theme = "poet"
disqusShortname = "springhispano"

[params]
  languageCode = "es-mx"
  forkGitHubUrl = "https://github.com/springhispano/website"
  tagline = "El ecosistema Spring en tu idioma"
  github = "SpringHispano"
  slack = "http://slack.springhispano.org"
  twitter = "SpringHispano"
  facebook = "https://www.facebook.com/groups/155793886960/"
  vimeo = "springhispano"
  googleplus = "https://plus.google.com/u/5/communities/102613290119984013640"
  avatar = "/avatar.png"
  disqusShortname = "springhispano"
